export interface Pet {
  id: number;
  name: string;
  species: string;
  size: string;
  age: string;
  city: string;
  tag: string;
  img: string;
  alt: string;
  gender: string;
  description?: string;
  shelter?: string;
  vaccinated?: boolean;
  neutered?: boolean;
  diet?: string;
  microchipped?: boolean;
  daysActive?: number;
}

export const petsData: Pet[] = [
  {
    id: 1,
    name: "Max",
    species: "Cães",
    size: "Grande",
    age: "Adulto",
    city: "São Paulo",
    tag: "Resgate recente",
    img: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&q=80&w=600",
    alt: "A majestic Golden Retriever sitting proudly in a sun-drenched park.",
    gender: "Macho",
    description: "Max is a gentle soul with a heart as big as his personality. Despite his \"Large\" classification for a Pug, he is truly a relaxed companion who loves nothing more than a quiet afternoon by your side. He was rescued from a difficult situation where he lacked the attention a social dog like him needs. He gets along famously with other dogs.",
    shelter: "Amigos do Totó ONG",
    vaccinated: true,
    neutered: true,
    diet: "Weight Control (Special Diet)",
    microchipped: true,
    daysActive: 4,
  },
  {
    id: 2,
    name: "Luna",
    species: "Gatos",
    size: "Pequeno",
    age: "Filhote",
    city: "Rio de Janeiro",
    tag: "",
    img: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=600",
    alt: "A curious calico kitten exploring a bright, modern living room.",
    gender: "Fêmea",
    description: "Luna is an energetic calico kitten looking for an active home. She loves toys, laser pointers, and sleeping on warm laps.",
    shelter: "Gatos do Rio",
    vaccinated: true,
    neutered: false,
    diet: "Kitten Formula",
    microchipped: true,
    daysActive: 12,
  },
  {
    id: 3,
    name: "Tobias",
    species: "Cães",
    size: "Médio",
    age: "Idoso",
    city: "Curitiba",
    tag: "Idoso",
    img: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=600",
    alt: "A gentle senior Beagle resting on a plush, cream-colored rug.",
    gender: "Macho",
    description: "Tobias is a sweet senior Beagle who spends most of his day napping. He is very calm, quiet, and friendly.",
    shelter: "Abrigo Curitiba",
    vaccinated: true,
    neutered: true,
    diet: "Senior Care",
    microchipped: true,
    daysActive: 28,
  },
  {
    id: 4,
    name: "Bella",
    species: "Cães",
    size: "Pequeno",
    age: "Adulto",
    city: "Belo Horizonte",
    tag: "",
    img: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=600",
    alt: "A playful French Bulldog standing alert on a clean, light-colored patio.",
    gender: "Fêmea",
    description: "Bella is a happy French Bulldog who loves attention and playing fetch. She is very friendly with kids.",
    shelter: "Patinhas de BH",
    vaccinated: true,
    neutered: true,
    diet: "Regular",
    microchipped: false,
    daysActive: 15,
  },
  {
    id: 5,
    name: "Oliver",
    species: "Gatos",
    size: "Pequeno",
    age: "Adulto",
    city: "Porto Alegre",
    tag: "Resgate recente",
    img: "https://images.unsplash.com/photo-1533733508377-386c62423b41?auto=format&fit=crop&q=80&w=600",
    alt: "A sleek grey tabby cat with striking green eyes, perched on a minimalist shelf.",
    gender: "Macho",
    description: "Oliver is a calm grey tabby cat. He is a bit shy at first but once he gets to know you, he will be your best buddy.",
    shelter: "Miados e Focinhos POA",
    vaccinated: true,
    neutered: true,
    diet: "Regular",
    microchipped: true,
    daysActive: 5,
  },
  {
    id: 6,
    name: "Thor",
    species: "Cães",
    size: "Grande",
    age: "Filhote",
    city: "Brasília",
    tag: "",
    img: "https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?auto=format&fit=crop&q=80&w=600",
    alt: "A fluffy German Shepherd puppy playing in a backyard.",
    gender: "Macho",
    description: "Thor is a beautiful German Shepherd puppy with lots of energy. He needs training and a lot of play time.",
    shelter: "Cães e Cia BSB",
    vaccinated: false,
    neutered: false,
    diet: "Puppy Premium",
    microchipped: true,
    daysActive: 2,
  },
  {
    id: 7,
    name: "Nina",
    species: "Gatos",
    size: "Médio",
    age: "Idoso",
    city: "Salvador",
    tag: "Idoso",
    img: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=600",
    alt: "A graceful Persian cat lounging on a soft linen cushion.",
    gender: "Fêmea",
    description: "Nina is a beautiful Persian cat who loves a quiet environment. She requires daily brushing for her long coat.",
    shelter: "Resgate Salvador",
    vaccinated: true,
    neutered: true,
    diet: "Hairball Control",
    microchipped: true,
    daysActive: 31,
  },
  {
    id: 8,
    name: "Pipoca",
    species: "Cães",
    size: "Pequeno",
    age: "Filhote",
    city: "Recife",
    tag: "Resgate recente",
    img: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=600",
    alt: "A tiny white Terrier mix puppy looking up with expectant eyes.",
    gender: "Fêmea",
    description: "Pipoca is a tiny Terrier puppy who is extremely loving and playful. She is great with other pets.",
    shelter: "Abrigo Focinho Feliz",
    vaccinated: true,
    neutered: false,
    diet: "Puppy Regular",
    microchipped: false,
    daysActive: 8,
  }
];
