import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f7fafd",
        "surface-dim": "#d7dade",
        "surface-bright": "#f7fafd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f8",
        "surface-container": "#ebeef2",
        "surface-container-high": "#e5e8ec",
        "surface-container-highest": "#e0e3e6",
        "on-surface": "#181c1f",
        "on-surface-variant": "#424842",
        "inverse-surface": "#2d3134",
        "inverse-on-surface": "#eef1f5",
        outline: "#737972",
        "outline-variant": "#c2c8c0",
        "surface-tint": "#4a654e",
        primary: "#4a654e",
        "on-primary": "#ffffff",
        "primary-container": "#8ba88e",
        "on-primary-container": "#233d29",
        "inverse-primary": "#b0ceb2",
        secondary: "#4d616d",
        "on-secondary": "#ffffff",
        "secondary-container": "#cde3f0",
        "on-secondary-container": "#516571",
        tertiary: "#5e5e5c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a2a19d",
        "on-tertiary-container": "#373835",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cceace",
        "primary-fixed-dim": "#b0ceb2",
        "on-primary-fixed": "#07200f",
        "on-primary-fixed-variant": "#334d38",
        "secondary-fixed": "#d0e6f3",
        "secondary-fixed-dim": "#b4cad7",
        "on-secondary-fixed": "#081e28",
        "on-secondary-fixed-variant": "#364954",
        "tertiary-fixed": "#e4e2de",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-tertiary-fixed": "#1b1c1a",
        "on-tertiary-fixed-variant": "#474744",
        background: "#f7fafd",
        "on-background": "#181c1f",
        "surface-variant": "#e0e3e6",
      },
      fontFamily: {
        quicksand: ["var(--font-quicksand)", "sans-serif"],
        nunito: ["var(--font-nunito-sans)", "sans-serif"],
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        "container-margin": "24px",
        gutter: "16px",
      },
    },
  },
  plugins: [],
};

export default config;
